name       : perl-compress-bzip2
version    : 2.26
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/R/RU/RURBAN/Compress-Bzip2-2.26.tar.gz : 5132f0c5f377a54d77ee36d332aa0ece585c22a40f2c31f2619e40262f5c4f0c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Interface to Bzip2 compression library
description: |
    The Compress::Bzip2 module provides a Perl interface to the Bzip2 compression library. A relevant subset of the functionality provided by Bzip2 is available in Compress::Bzip2.

    NOTE: Compress::Bzip2 is not well integrated into PerlIO, use the preferred IO::Compress::Bzip2 instead.
builddeps  :
    - bzip2-devel
    - perl-test-leaktrace
    - perl-test-pod
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
